version: '3.8'

services:
  ai-voice-agent:
    build: .
    container_name: ai-voice-agent
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    networks:
      - ai-voice-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ai-voice-network:
    driver: bridge
